ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Users\hp\Pictures\Screenshots\Screenshot (1).png")
Sleep(2000)
ControlFocus("Open","","Button1")
ControlClick("Open","","Button1")